name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main # Dispara o build sempre que você enviar código para a branch principal
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: npm install
        
      - name: Build TypeScript Project
        run: npm run build # Aqui o GitHub transforma seu TS em HTML/JS
        
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PET_FINDER_PRO }}'
          channelId: live
          projectId: pet-finder-pro